# Generated by Django 2.0.1 on 2018-01-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0003_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='text',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='statement',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='name',
            field=models.CharField(default='legacy', max_length=254),
            preserve_default=False,
        ),
    ]
